# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ae557ca874d7f2ffa17995a1260bc15ab5d5bcbf0a560247ca8ac17d8a8ee388324032b4ff522e07bbe91688d16f9b8ab083a591fc8b88d6b0aff6d2fb4603

test:
  secret_key_base: d53f6f9ae976a6aa2e2a7aa4bca8b49486179101d4f54e6f2845b64ad54c25dbee789c83a1a6a6220c7e06f940af1be8f5e9f067cf18face3eba34619773645d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
